---
- name: Ensure crontab script folder exists
  tags: cron
  include_tasks:
    file: roles/utils/cron/tasks/start-cron-jobs.yaml
    apply: { tags: [ "cron" ] }
  vars:
    cron_script_files:
      - script: maintenance-dev.sh
        minute: "30"
        hour: "0"