---
- name: Add naiveproxy to service list
  tags: np
  set_fact:
    services: "{{ services + [ service ] }}"
  vars:
    service:
      name: naiveproxy
      service_config: templates/naiveproxy/service.yaml.j2
      folders:
        - "{{ svc_data_dir }}/naiveproxy/config"
        - "{{ svc_data_dir }}/naiveproxy/data/html"
        - "{{ svc_data_dir }}/naiveproxy/log"
      templates:
        - src: templates/naiveproxy/Caddyfile.j2
          dest: "{{ svc_data_dir }}/naiveproxy/config/Caddyfile"