---
- name: Install grafana
  tags: grafana
  import_role:
    name: grafana.grafana.grafana
  vars:
    grafana_port: "{{ secrets.telemetry_store.grafana.port }}"
    grafana_security:
      admin_user: "{{ secrets.telemetry_store.grafana.admin_username }}"
      admin_password: "{{ secrets.telemetry_store.grafana.admin_password }}"