---
- name: "Get all network interfaces in subnet: {{ subnet_item.name }}"
  include_tasks:
    file: roles/utils/net/tasks/get-all-ifs-in-subnet.yaml
    apply: { tags: [ "always" ] }
  vars:
    subnet: "{{ subnet_item }}"

- name: "Deploy dnsmasq configuration for subnet: {{ subnet_item.name }}"
  template:
    src: dnsmasq.dhcp.conf.j2
    dest: "/etc/dnsmasq.d/dhcp.{{ subnet_item.name }}.conf"
