---
- name: "Ensure {{ service.name }} service definition folder exists"
  become: false
  file:
    path: "{{ svc_services_dir }}"
    state: directory

- name: "Ensure {{ service.name }} config folder exists"
  become: false
  file:
    path: "{{ service.config_dir }}"
    state: directory

- name: "Ensure {{ service.name }} data folder exists"
  become: false
  file:
    path: "{{ service.data_dir }}"
    state: directory

- name: Generate files from templates
  become: false
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ service.templates }}"