---
- name: Install python 3
  tags: python
  package:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - python3-setuptools

- name: Install python packages via pip
  tags: python
  become: false
  pip:
    name:
      - docker
      - docker-compose