---
- name: Remove default user if not desired
  tags: cleanup
  when: item != desired_user
  user:
    name: '{{item}}'
    state: absent
    remove: true
  with_items: '{{users_to_remove}}'
  ignore_errors: true
