---
- name: Remove default user
  tags: cleanup
  when: keep_default_user is not defined or not keep_default_user
  user:
    name: '{{item}}'
    state: absent
    remove: true
  with_items: '{{users_to_remove}}'
  ignore_errors: true
