---
- name: Ensure crontab script folder exists
  tags: cron
  include_tasks:
    file: roles/utils/cron/tasks/start-cron-jobs.yaml
    apply: { tags: [ "frps" ] }
  vars:
    cron_script_files:
      - script: maintenance-common.sh
        minute: "0"
        hour: "0"