---
- name: Add cloudflared databus tunnel to service list
  tags: cloudflared
  set_fact:
    services: "{{ services + [ service ] }}"
  vars:
    service:
      name: cloudflared-databus
      service_config: templates/cloudflared/service.yaml.j2
      tunnel:
        name: databus
        token: "{{ secrets.cloudflare.tunnel.databus.token }}"
        log_level: debug
      folders: 
        - "{{ svc_data_dir }}/cloudflared/databus/log"
      templates: []