---
- name: Check command apt exists
  shell: command -v apt >/dev/null 2>&1
  register: is_apt_exists 
  ignore_errors: true

- name: Update package source using apt
  when: is_apt_exists.rc == 0
  command: apt update